---
# tasks file for nginx

- name: Add nginx repository
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - nginx
    - packages
    - nginx-packages

- name: Install latest nginx packages
  yum:
    name:
      - nginx
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - packages
    - nginx-packages

# - name: Create site directory
#   file:
#     path: "{{ nginx_default_www_directory }}"
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
#   tags:
#     - nginx
#     - configuration
#     - nginx-configuration

# - name: Copy index.html to the remote host
#   template:
#     src: index.html.j2
#     dest: "{{ nginx_default_www_directory }}/index.html"
#     owner: root
#     group: root
#     mode: '0644'
#     # serole: 'httpd_sys_content'
#   tags:
#     - nginx
#     - configuration
#     - nginx-configuration

- name: Copy nginx.conf to the remote host
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_nginx
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - configuration
    - nginx-configuration

- name: Copy /etc/nginx/conf.d/default.conf to the remote host
  template:
    src: conf.d/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_nginx
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - configuration
    - nginx-configuration

- name: Enable and start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - service
    - nginx-service

- name: Debug msg
  debug:
    msg: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}"
  with_items: "{{ groups[backend_group] }}"
  tags:
    - nginx

# when: inventory_hostname in groups['group']

# - name: flush_handlers
#   meta: flush_handlers