---
# tasks file for nginx

- name: Add EPEL repository
  yum:
    name:
      - epel-release
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - packages
    - nginx-packages

- name: Install latest nginx packages
  yum:
    name:
      - nginx
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - packages
    - nginx-packages

- name: Enable and start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - service
    - nginx-service

- name: Create site directory
  file:
    path: "{{ nginx_default_www_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - nginx
    - configuration
    - nginx-configuration

- name: Copy index.html to the remote host
  template:
    src: index.html.j2
    dest: "{{ nginx_default_www_directory }}/index.html"
    owner: root
    group: root
    mode: '0644'
    selevel: _default
    seuser: _default
    serole: httpd_sys_content
  tags:
    - nginx
    - configuration
    - nginx-configuration

- name: Copy nginx.conf to the remote host
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx
  when:
    - ansible_distribution == "CentOS"
  tags:
    - nginx
    - configuration
    - nginx-configuration

