---
- name: Common
  hosts: all
  become: true
  roles:
    - common
  tags:
    - common

- name: Frontend
  hosts:
    - STAG_frontend
    - PROD_frontend
  become: true
  roles:
    - nginx

- name: Backend
  hosts: 
    - STAG_backend
    - PROD_backend
  become: true
  roles:
    - apache
    - php

- name: DB
  hosts: 
    - STAG_db
    - PROD_db
  become: true
  roles:
    - mysql
  tags:
    - mysql