---
# tasks file for wordpress
# - name: Download latest version of WordPress
#   get_url:
#     url: http://wordpress.org/latest.tar.gz
#     dest: ~/latest.tar.gz
#   tags:
#     - wordpress
#     - download
#     - wordpress-download

- name: Download and unpack WordPress
  unarchive:
    src: "{{ wordpress_download_url }}"
    dest: "{{ wordpress_directory }}"
    owner: apache
    group: apache
    mode: 0640
    remote_src: yes
  tags:
    - wordpress
    - download
    - unpack
    - wordpress-download
    - wordpress-unpack
