---
- name: Download and unpack WordPress
  unarchive:
    src: "{{ wordpress_download_url }}"
    dest: "{{ wordpress_directory }}"
    owner: apache
    group: apache
    mode: 0750
    remote_src: yes
  tags:
    - wordpress
    - download
    - unpack
    - wordpress-download
    - wordpress-unpack

- name: Create ./wp-content/uploads directory
  file:
    path: "{{ wordpress_directory }}/wp-content/uploads"
    state: directory
    owner: apache
    group: apache
    mode: 0640

# - name: Create .htaccess file
#   template:
#     source: 