---
- name: Download and unpack WordPress
  unarchive:
    src: "{{ wordpress_download_url }}"
    dest: "{{ wordpress_directory }}"
    owner: apache
    group: apache
    mode: 0750
    remote_src: yes
  tags:
    - wordpress
    - download
    - unpack
    - wordpress-download
    - wordpress-unpack

- name: Create ./wp-content/uploads directory
  file:
    path: "{{ wordpress_directory }}/wp-content/uploads"
    state: directory
    owner: apache
    group: apache
    mode: 0640
  tags:
    - wordpress
    - configuration
    - wordpress-configuration

- name: Copy wp-config.php.j2 to the remote host
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_directory }}/wordpress/wp-config.php"
    owner: apache
    group: apache
    mode: 0750
  tags:
    - wordpress
    - configuration
    - wordpress-configuration
