---
# tasks file for mysql

- name: Install and start MySQL on CentOS
  block:
  - name: Add MySQL repository
    yum:
      name: "{{ mysql_repo_packege }}"
      state: present

  - name: Install latest MySQL packages
    yum:
      name:
        - mysql-server
        - MySQL-python
      state: latest
      update_cache: yes

  - name: Enable and start MySQL service
    service:
      name: mysqld
      state: started
      enabled: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - mysql
    - packages
    - mysql-packages

- name: Change MySQL root password
  block:
    - name: Try to login with a password and set password for root
      mysql_user:
        host_all: yes
        login_user: "{{mysql_login_user}}"
        login_password: "{{mysql_login_password}}"
        name: root
        password: "{{ mysql_root_password }}"
        state: present
  rescue:
    - name: Try to login without a password and set password for root
      mysql_user:
        host_all: yes
        name: root
        password: "{{ mysql_root_password }}"
        state: present
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Remove the test database
  mysql_db:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: test
    state: absent
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Run SQL queries
  block:
    - name: Copy mysql_secure_installation.sql to the remote host
      copy:
        src: mysql_secure_installation.sql
        dest: ~/
        mode: '0600'

    - name: Execute mysql_secure_installation.sql
      mysql_db:
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        name: all
        state: import
        target: ~/mysql_secure_installation.sql
      # notify:
      #   - delete mysql_secure_installation.sql
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Copy my.cnf to the remote host
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart mysql
  tags:
    - mysql
    - configuration
    - mysql-configuration
