---
# tasks file for mysql

- name: Install and start MySQL on CentOS
  block:
  - name: Add MySQL repository
    yum:
      name: "{{ mysql_repo_packege }}"
      state: present

  - name: Install latest MySQL packages
    yum:
      name:
        - mysql-server
        - MySQL-python
      state: latest
      update_cache: yes

  - name: Enable and start MySQL service
    service:
      name: mysqld
      state: started
      enabled: yes
  when:
    - ansible_distribution == "CentOS"
  tags:
    - mysql
    - packages
    - mysql-packages

- name: Change MySQL root password
  mysql_user:
    host_all: yes
    name: root
    password: "{{ mysql_root_password }}"
    state: present
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Copy .my.cnf to the remote host
  template:
    src: .my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: '0400'
  tags:
    - mysql
    - configuration
    - mysql-configuration

- name: Removes all anonymous user accounts
  mysql_user:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: ''
    host_all: yes
    state: absent
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Removes root user account for non-localhost
  mysql_user:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: root
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Remove the test database
  mysql_db:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: test
    state: absent
  tags:
    - mysql
    - secure
    - mysql-secure

- name: Copy my.cnf to the remote host
  template:
    src: etc/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_mysql
  tags:
    - mysql
    - configuration
    - mysql-configuration

- name: Create databases
  mysql_db:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_databases }}"
  tags:
    - mysql
    - mysql-db

- name: Create users
  mysql_user:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: "{{ mysql_users }}"
  tags:
    - mysql
    - users
    - mysql-users

- name: Create dynamic users
  mysql_user:
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    name: "{{ dynamic_mysql_users.name }}{{ '%2x'|format(item) }}"
    host: '%'
    password: "{{ dynamic_mysql_users.password }}{{ '%2x'|format(item) }}"
    # priv: "{{ item.priv }}"
    state: present
  loop: "{{ range(1, dynamic_mysql_users.count | default(0)) | list }}"
  when: dynamic_mysql_users
  tags:
    - mysql
    - users
    - mysql-users

# - name: flush_handlers
#   meta: flush_handlers