---
# tasks file for php
- name: Install latest php packages
  yum:
    name:
      - php
      - php-gd
      - php-cli
    state: latest
    update_cache: yes
  notify:
    - restart_httpd
  when:
    - ansible_distribution == "CentOS"
  tags:
    - php
    - packages
    - php-packages

- name: copy info.php to the remote host
  copy:
    src: info.php
    dest: /var/www/html/info.php
    # owner: root
    # group: root
    mode: '0644'
