---
# tasks file for php
- name: Install latest php packages
  yum:
    name:
      - php
      - php-gd
      - php-cli
      - php-mysql
    state: latest
    update_cache: yes
  notify:
    - restart_httpd
  when:
    - ansible_distribution == "CentOS"
  tags:
    - php
    - packages
    - php-packages
